# Generated by Django 3.0.4 on 2020-03-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='comments',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='room_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
