# Generated by Django 3.0.4 on 2020-03-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200322_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
