# Generated by Django 3.0.4 on 2020-03-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20200322_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='comments',
        ),
    ]
