# Generated by Django 3.0.4 on 2020-03-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patients_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
