# Generated by Django 3.0.4 on 2020-03-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patients_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='comments',
            field=models.CharField(default='asdf', max_length=255),
        ),
    ]
