# Generated by Django 3.0.4 on 2020-03-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20200322_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='comments',
            field=models.CharField(blank=True, default='asdf', max_length=255),
        ),
    ]
