# Generated by Django 3.0.4 on 2020-03-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20200322_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='comments',
            field=models.IntegerField(),
        ),
    ]
