# Generated by Django 3.0.4 on 2020-03-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20200322_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='room_num',
            new_name='room_number',
        ),
    ]
