# Generated by Django 3.0.4 on 2020-03-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_auto_20200322_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='id',
        ),
        migrations.AlterField(
            model_name='patients',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
