# Generated by Django 3.0.4 on 2020-03-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_auto_20200327_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
